### ISSUE TITLE
可以支持一下2024吗，谢谢了

### ISSUE THREAD

**Issue by liango2** [z-soulx/CodeReadingMarkNotePro#1]
可以支持一下 intellij 2024吗，谢谢了

**Comment by z-soulx** [comment]
> 可以支持一下 intellij 2024吗，谢谢了

可以，预计周末支持，也欢迎你提交pr来支持

**Comment by z-soulx** [comment]
> 可以支持一下 intellij 2024吗，谢谢了
[2024.1.0](https://github.com/z-soulx/CodeReadingMarkNotePro/tree/2024.1.0) 分支已解决，市场正在审核中
