### ISSUE TITLE
在CodeReadingMarkNotePro管理界面修改注释不会自动同步代码上的注释，添加注释时不能输入中文

### ISSUE THREAD

**Issue by Mejituu** [z-soulx/CodeReadingMarkNotePro#3]
重新关闭并打开代码对应的文件就能显示新的注释，不过管理界面修改注释可以输入中文
版本2024.2.2

**Comment by Mejituu** [comment]
在jbr21的情况下，删除标签会报错什么长度-1，17没试过

**Comment by z-soulx** [comment]
> 在jbr21的情况下，删除标签会报错什么长度-1，17没试过

请问有异常记录吗？

**Comment by z-soulx** [comment]
> 重新关闭并打开代码对应的文件就能显示新的注释，不过管理界面修改注释可以输入中文 版本2024.2.2

我周末看看，我记得我修复过这个bug

**Comment by Mejituu** [comment]
> > 在jbr21的情况下，删除标签会报错什么长度-1，17没试过
> 
> 请问有异常记录吗？

晚点我再看看 应该是能复现

**Comment by z-soulx** [comment]
> > 重新关闭并打开代码对应的文件就能显示新的注释，不过管理界面修改注释可以输入中文 版本2024.2.2
> 
> 我周末看看，我记得我修复过这个bug

已修复，新版已上传，等待官方审核，也可直接下载GitHub上的最新包手动安装
- fix：中文输入+偶尔代码注释不能立马展示
