### ISSUE TITLE
你好, 无法输入汉字.

### ISSUE THREAD

**Issue by 834116404** [z-soulx/CodeReadingMarkNotePro#4]
![Uploading image.png…]()

汉字无法输入, 我用的搜狗输入法, MacBook电脑

**Comment by 834116404** [comment]
![Uploading iShot_2024-11-15_16.57.38.png…]()

**Comment by 834116404** [comment]
![Uploading iShot_2024-11-15_16.57.38.png…]()

**Comment by 834116404** [comment]
咋不能输入图片...

**Comment by z-soulx** [comment]
已经修复 #3

**Comment by 834116404** [comment]
谢谢了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月17日(周日) 下午4:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [z-soulx/CodeReadingMarkNotePro] 你好, 无法输入汉字. (Issue #4)




 
已经修复 #3

**Comment by 834116404** [comment]
你好, 咱们修复后的 插件预计什么时候上线

**Comment by z-soulx** [comment]
> 你好, 咱们修复后的 插件预计什么时候上线

已修复，新版已上传，等待官方审核(官方显示2工作日左右)，也可直接下载GitHub上的最新包手动安装 #3

**Comment by 834116404** [comment]
咱们最新包下载地方在github哪里, 我没找到..

**Comment by 834116404** [comment]
找到了 
![image](https://github.com/user-attachments/assets/f9a07dbb-4f91-4326-9a86-b06a13074016)
